name: SonarCloud Analysis

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:  # SonarCloud authentication token
        required: true
      SONAR_ORG:  # SonarCloud organization
        required: true
      SONAR_HOST_URL:  # SonarCloud host URL
        required: true

jobs:
  sonarcloud-analysis:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Perform SonarCloud Analysis
      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
          SONAR_HOST_URL: https://sonarcloud.io
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
